workflows:
  build-android:
    name: Build Android APK
    max_build_duration: 30
    environment:
      vars:
        JAVA_VERSION: 11
    scripts:
      - name: Permissão gradlew
        script: chmod +x gradlew
      - name: Build APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
